/* Puts mega-net's image and its far-call trampoline into memory at
 * startup. Both must live at fixed physical addresses before any
 * meganet_call(): the trampoline at $1600, the page mega-net reserves
 * in every client, performs the MAP/JSR into bank 4, and bank 4 holds
 * the image.
 *
 * The image travels as a second file on the same .d81 as the client and
 * is streamed into bank 4 below. Embedding it once cost 22 KB of the
 * $2001-$D000 window for data read exactly once, leaving no room for
 * features; a read from the SD card's FAT root would have broken the
 * one-disk rule, since a mounted .d81 is reached through CBM DOS. The
 * trampoline stays embedded: at a hundred bytes it is not worth a file,
 * and it has to be in place before anything else runs. */
#include "mega65/memory.h"
#include "meganet_tramp.h"      /* generated by ../mega-net/build.py abi */
#include "meganet.h"            /* MEGANET_TR, the reserved page */
#include "m65_cbmdos.h"
#include "m65_boot.h"

/* The image goes to bank 4 at $42000, the trampoline to $1600, the page
 * mega-net reserves in every client (its mailbox is what a BASIC
 * program pokes, so it is one address everywhere). This client's F011
 * sector buffer, once at $1600, moved into .bss to make way (mega-net
 * REQUIREMENTS.md 5.10). */
#define ETH_DEST 0x42000L
#define TRAMPOLINE_DEST ((long)MEGANET_TR)   /* $1600, the page mega-net reserves */

/* Which drive ETHBIN was found on, so the rest of the program can default
 * to the disk the user actually started from. */
unsigned char boot_drive = 0;

unsigned char m65_boot_load(const char **err)
{
  mega65_io_enable();

  lcopy((long)meganet_call_bin, TRAMPOLINE_DEST, MEGANET_CALL_BIN_SIZE);

  /* Search both drives rather than assuming drive 0.
   *
   * ETHBIN ships on the same .d81 as the client, so it is wherever that
   * disk is mounted -- and the MEGA65 will happily mount it as device 9.
   * Hardcoding drive 0 meant the client could be loaded from drive 9 and
   * then refuse to start, reporting a missing file that was on the very
   * disk it had just been read from. Try 0, then 1. */
  boot_drive = 0;
  if (cbmdos_load("MEGANET", 0, ETH_DEST, MEGANET_BIN_SIZE) != MEGANET_BIN_SIZE) {
    boot_drive = 1;
    if (cbmdos_load("MEGANET", 1, ETH_DEST, MEGANET_BIN_SIZE) != MEGANET_BIN_SIZE) {
      *err = "MEGANET not found on drive 8 or 9 (or wrong size)";
      return 0;
    }
  }

  /* Read back one byte of each as a cheap sanity check that the copies
   * landed -- bank 4/5 addressing has bitten us before (writes to bank 6
   * silently did nothing, since this machine only has banks 0-5). */
  if (lpeek(TRAMPOLINE_DEST + MEGANET_TR_CALL_OFF) != 0x08) { /* PHP, the call entry */
    *err = "trampoline did not land";
    return 0;
  }
  if (lpeek(ETH_DEST) != 0x4c) { /* the jump table starts with a JMP */
    *err = "mega-net did not land at $42000";
    return 0;
  }

  *err = 0;
  return 1;
}

void m65_own_vectors(void)
{
  meganet_own_vectors();                          /* the kit's: mega-net REQUIREMENTS.md 5.18 */
}
